CODEOWNERS

chore: adds CODEOWNERS

---

README.md

This PR implements the first version of the README file

first Readme version

---

.github/workflows/ci.yaml

Actually an excuse to run the CI against last envoy master.

chore: adds e2e envoy image message before test.

---

magefile.go

I have found performance to be way different based on the initial heap size. It does seem to show tinygo's poor allocator performance. Importantly it's simple to configure it now for testing, and I went ahead and raised it. Actually 512MB seemed to make a huge impact but seemed way too much

Allow configuring initial heap and set to 100MB instead of 1MB

---

internal/re2/re2.go

This sets to the same value as the default, 8MB. Notably, a small size prevents re2 from using DFA and it will use NFA instead. With the default, when running FTW locally I see it's RAM usage grow until around 1.5GB which does seem pretty huge, while setting this to ~100KB probably causes most regex's to become NFA and runtime is much slower, but RAM never goes above ~500MB.
Need to investigate more whether the default is OK or not, but in the meantime this allows it to be configured when testing

Allow setting ram usage of regular expressions

---

main_test.go

Now that proxy-wasm-go-sdk supports property, we can add tests

Add test case for request protocol

---

buildtools/tinygo/wasi-libc.Dockerfile

Commit `268140ae40185f2b2b79df9e0550cc4f7287692c` includes:
- https://github.com/tinygo-org/tinygo/pull/3245
- https://github.com/tinygo-org/tinygo/pull/3252

chore: upgrades tinygo.

---

.github/workflows/ci.yaml

Run the jobs for git tags so that images are produced for releases.

Run build and publish images for Git tags

---

internal/agc/gc_conservative.go
internal/agc/gc_stack_portable.go

https://github.com/tinygo-org/tinygo/pull/3291

Copy in stack chain workaround from upstream

---

.github/workflows/buildtools-tinygo.yaml

More tinygo churn than expected so will be good to have reproducible tags

Tag tinygo image with sha as well

---

buildtools/re2/Dockerfile
buildtools/re2/re2.patch

Realized the flags being patched were already overridable

Reduce re2 patching

---

buildtools/aho-corasick/src/lib.rs

I was looking into cleaning up the rust code referring to https://stackoverflow.com/a/46677043
But while examining the code I noticed there is probably a memory leak - I think I thought `String::from` wraps a string but then I found https://stackoverflow.com/a/65974325. Well `from` is a generic function in Rust so not sure how you're supposed to guess it's behavior 🤷

Fix possible rust memory leak and use FFI idioms

---

go.mod
go.sum
wasmplugin/plugin.go

Upgrade to latest coraza and fix nightly build failures after https://github.com/corazawaf/coraza/commit/033db8452e163082e5856827a29b78db4d08c840

Fix error callback registration

---

go.mod
go.sum
main_test.go
wasmplugin/plugin.go

- Updates coraza
- implements call to SetServerName (https://github.com/corazawaf/coraza/pull/572)

adds call to SetServerName

---

go.mod
go.sum
main_test.go
wasmplugin/rules/coraza-demo.conf
wasmplugin/rules/coraza.conf-recommended.conf

This PR fixes the nightly check updating coraza and fixing accordingly the tests. https://github.com/corazawaf/coraza/pull/612 removed some default values, therefore this PR adds explicitly some directives to make the tests work as expected

chore: updates coraza, fixes tests accordingly

---

go.mod
go.sum
main_test.go
wasmplugin/logger.go
wasmplugin/plugin.go
wasmplugin/plugin_test.go

PoC using the new logger API
Depends on https://github.com/corazawaf/coraza/pull/682
Ping @manojgop @ns-sundar

chore: uses new coraza logger.

---

README.md

Fixes #178 
Thanks @spacewander

Update README to reflect wasilibs usage

---

README.md
example/envoy-config.yaml
magefiles/magefile.go
wasmplugin/config.go
wasmplugin/config_test.go
wasmplugin/metrics.go
wasmplugin/plugin.go

fix https://github.com/corazawaf/coraza-proxy-wasm/issues/174
adding metrics label on statsd metrics to distinguish metrics based on user input.

feat: introduce custom labels on metrics

---

wasmplugin/plugin.go

Before we did not have a way to know when an interruption was already handled whether it was a local response or a programming bug, with this change we will know for sure which phase triggered the interruption and hence whether this is a programming bug or a normal local response.
Related to https://github.com/corazawaf/coraza-proxy-wasm/issues/181

chore: improves logging for interruptions handled.

---

README.md
example/envoy-config.yaml
ftw/envoy-config.yaml
main_test.go
wasmplugin/config.go
wasmplugin/config_test.go
wasmplugin/metrics.go
wasmplugin/plugin.go

This PR simplifies the logic around per authority directives to make it easier to digest and consume, also fixes some state problems in metrics and logs.

chore: refactors per authority directives.

---

.github/workflows/ci.yaml

Attempt to fix multiplatform build. Ref https://docs.docker.com/build/ci/github-actions/multi-platform/

ci: install qemu [Multi-platform busybox image]
