corazawaf/coraza-proxy-wasm

.github/workflows/buildtools-tinygo.yaml, buildtools/tinygo/Dockerfile, buildtools/tinygo/wasi-libc.Dockerfile
Former doesn't need to be multiarch
=> Split TinyGo docker build into wasi-libc and tinygo

.github/workflows/nightly-coraza-check.yaml
Usually we change tinygo or go version on ci.yaml and forget to keep track of the change in the nightly.
=> chore: makes nightly check to run on ci.yaml change.

main.go, main_test.go
This changes the variable name for the uri to represent what it is even if the HTTP pseudo header name is :path. This helps with porting as a mistake is easier otherwise.
=> Clarifies the :path pseudo-header includes query params

go.mod, magefile.go
Currently we depend on compiling the ahocorasick with go 1.19 whereas attempting to compi
le it with 1.18 might lead to errors, hence the enforcement of version.
=> Adds version checks

magefile.go
Currently we aim to parse a <mayor>.<minor>.<patch> version which might not be the case as sometimes version is 'go version go1.19 darwin/arm64'.
Ping @M4tteoP
=> fix: fixes go version parsing.

README.md, config.go, config_test.go, example/envoy-config.yaml, ftw/envoy-config.yaml, internal/operators/rx.go, main.go, main_test.go, testdata/fake_crs/REQUEST-911.conf
This PR changes the config to simplify it and let users to load it directly. One thing we must consider here is:
a. folder structure of `rules` is now part of the public API (maybe we should add a check to not to break it)
b. we should be able to validate includes in standalone mode (i.e. without running them in the extension).
=> Simplify config

.github/workflows/buildtools-tinygo.yaml, buildtools/tinygo/Dockerfile, buildtools/tinygo/wasi-libc.Dockerfile
This builds TinyGo with https://github.com/tinygo-org/tinygo/pull/3245. Ideally we stick to released TinyGo, but this change affects us dramatically.
=> Add back TinyGo docker build

go.mod, go.sum, init_tinygo.go, internal/agc/doc.go, internal/agc/gc_conservative.go, internal/agc/gc_globals.go, internal/agc/gc_stack_portable.go, internal/agc/mem.go, internal/bodyprocessors/xml.go, internal/gc/doc.go
Something about https://github.com/corazawaf/coraza/commit/635fad46ea34169ee11ed1cfee198692fb29ff5e caused allocations to happen in initialization before the gc package can setup the heap. For normal code this is fine so it would be too much of a restriction to ensure coraza never does this and we need to handle it here.
Go executes init functions for imports in alphabetical order it seems (I tried putting the import explicitly above the others to no effect). Currently the only option seems to be renaming the package - as a followup to the change in TinyGo to allow custom malloc I may try to improve this, but that would be a more intrusive change and so hopefully we can be decoupled even if we need this trick.
Perhaps we can just name this GC implementation the "anuraaga gc" and then the …
=> Rename gc package for initialization ordering

rules/coraza-demo.conf, rules/coraza.conf-recommended.conf
Ports https://github.com/corazawaf/coraza/pull/470 to coraza-proxy-wasm.
=> Fix parser activation rules in recommended configs

ftw/docker-compose.yml, ftw/envoy-config-nowasm.yaml, ftw/envoy-config.yaml, ftw/httpbin/Dockerfile
Tests complete much faster 32s vs 58s locally, without compatibility issues like previous attempt
=> Replace httpbin with go-httpbin

README.md, config_test.go, example/envoy-config.yaml, fs.go, ftw/envoy-config.yaml, main.go, main_test.go
This feature allows users to use @recommended-conf instead of 'coraza.conf-recommended', etc. as a way to abstract the location of this configurations and allowing users to mount volumes with config in the future without collision.
=> feat: adds configuration mapping.

main.go, rules/fs.go, rules/fs_test.go
Today there is no practical way to validate the rules before the extension is loaded. The seclang `parser` package in Coraza is internal, but using it directly is not enough to properly validate a set of rules. Access to the rule filesystem is needed to validate that `Include` directives do not point to unexisting files.
Validating rules beforehand is IMO an important UX topic. Without it, invalid rules would cause the extension to error and not load, and that will only happen at runtime, leaving just some traces in the proxy logs. users may not notice and assume their WAF is running while it's not.
This PR exposes the rules FS so coraza can be loaded as a library with this filesystem, in order to do proper rule validation.
Note that the `fs.go` has been moved to the `rules` package since …
=> Expose the rules filesystem for offline rule validation

ftw/envoy-config.yaml, main.go, main_test.go, rules/fs.go, rules/fs_test.go
Small PR that follows https://github.com/corazawaf/coraza-proxy-wasm/pull/79#discussion_r1022610150, adds `@crs-setup-conf-example` keyword.
=> adds @crs-setup-conf to configuration mapping

buildtools/tinygo/wasi-libc.Dockerfile, magefiles/magefile.go
While the upstream PR is stalled, it will either be merged or we will need to just continue with a fork, as it's still better than being locked to a reverted commit.
=> Switch TinyGo to custom gc fork

.github/workflows/nightly-coraza-check.yaml, go.mod, go.sum, wasmplugin/plugin.go
This PR:
- Upgrades Coraza fixing breaking changes that lead to Nightly Check failure
- Updates deprecated `set-output` command following https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples
=> chore: upgrades coraza, fixes nightly check

example/docker-compose.yml
Sets an higher maximum size of request or response bodies (default is [1Mib](https://github.com/mccutchen/go-httpbin)) for testing purposes with big payloads.
=> chore: sets MAX_BODY_SIZE for go-httpbin

e2e/docker-compose.yml, e2e/e2e-example.sh, example/docker-compose.yml, ftw/docker-compose.yml, magefiles/magefile.go, wasmplugin/plugin.go
Follows https://github.com/corazawaf/coraza-proxy-wasm/pull/124.
Fixing the CI pipeline to test multiple envoy versions, showed that multiple requests are hanging until timeout running coraza-proxy-wasm on Envoy `1.24`.
It happens because in certain circumstances `handleInterruption`  (with internally `proxywasm.SendHttpResponse`) is triggered twice, and in Envoy 1.24 multiple sendLocalResponse behaviour has been fixed with https://github.com/envoyproxy/envoy/pull/23049.
This PR proposes to add a boolean value to track if intervention occurred, avoiding calling twice sendLocalResponse. This check is something also done on some C++ ModSec Wasm filter implementations (e.g. https://github.com/intel/modsecurity-wasm-filter/blob/main/wasmplugin/envoy-wasm-modsecurity.cc#L373-L375)
=> Fix: avoids double interruption

README.md, wasmplugin/rules/crs-setup-demo.conf, wasmplugin/rules/crs-setup.conf.example
Running the CRS in Anomaly Scoring Mode (default mode), the anomaly score evaluation happens at the end of phase 2 (request body) and phase 4 (response body). Enabling [early blocking](https://coreruleset.org/20220302/the-case-for-early-blocking/), the evaluation will happen also at the end of phase 1 (request header) and phase 3 (response headers).
I think that this feature is really handy for proxy-wasm in order to mitigate malicious payloads sent upstream: the earlier we raise an interruption, the better (See also https://github.com/corazawaf/coraza-proxy-wasm/pull/128).
As a matter of example: CRS rule `913100` is triggered at phase 1 and looks for malicious User-Agents.
Request: `curl -I --user-agent "Grabber/0.1 (X11; U; Linux i686; en-US; rv:1.7)" -H "Host: localhost" -H "Accept: …
=> Enables CRS early blocking

go.mod, go.sum, main_test.go, wasmplugin/plugin.go
Adrress broken changes introduced by [Flatters WAF config API for better flexibility in setting memory limits and enabling BodyAccess #503](https://github.com/corazawaf/coraza/pull/503).
The PR will be rebased after https://github.com/corazawaf/coraza-proxy-wasm/pull/131.
=> address Flattered limits in Coraza

buildtools/wasi-sdk/Dockerfile
For newer binaryen package and to match upstream's (still not made public...) image
=> Use ubuntu base image for wasi-sdk

README.md, go.mod, go.sum, wasmplugin/rules/coraza-demo.conf, wasmplugin/rules/coraza.conf-recommended.conf
Follows [Corrects SecDebugLogLevel doc, reorders logs levels #519](https://github.com/corazawaf/coraza/pull/519):
- updates some SecDebugLogLevel directives
- updates `.conf` files with the new levels
=> chore: updates debug log levels

wasmplugin/plugin.go, wasmplugin/plugin_test.go
Currently we aim to resolve target port from the hostport, however if the target port as string is empty (most likely due to an error in the former operation) we should not attempt to turn that into an integer.
=> chore: avoids resolving target port if targetPortStr is empty.

.github/workflows/ci.yaml, Dockerfile
* Provides a ready-to-use `coraza-proxy-wasm` container image based on busybox that can be used as an `initContainer` of an envoy pod using [official images](https://hub.docker.com/r/envoyproxy/envoy) without having to build your own.
Basic example of a kubernetes manifest : 
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: envoy-coraza
labels:
app: envoy-coraza
...
spec:
initContainers:
- name: init-wasm
image: ghcr.io/corazawaf/coraza-proxy-wasm:busybox
command: ["/bin/sh"]
args: ["-c", "cp /plugin.wasm /build/main.wasm"]
volumeMounts:
- name: wasm
mountPath: "/build/"
containers:
- name:  envoy-coraza
image:  envoyproxy/envoy:v1.23-latest
volumeMounts:
- name: envoy-coraza
mountPath: /etc/envoy/
- name: wasm
mountPath: "/build/"
volumes:
- name: wasm
emptyDir: {}
```
=> Feat: add busybox based image build

.github/workflows/ci.yaml
Fixes container images build order so that `scratch`  image is the default in gh registry
=> Fix: container build order

go.mod, go.sum
This updates [wazero](https://wazero.io/) to [1.0.0-rc.1](https://github.com/tetratelabs/wazero/releases/tag/1.0.0-rc.1). This version does not change any public API, but it delivers several bug fixes and improvements; including
* Full support to the WASI test suite and other third-party integration tests
* Fix for an issue with the context cancellation API
* A number of optimizations to reduce compilation overhead
It also updates [tetratelabs/proxy-wasm-go-sdk](https://github.com/tetratelabs/proxy-wasm-go-sdk) to [0.22.0](https://github.com/tetratelabs/proxy-wasm-go-sdk/releases/tag/v0.22.0)
which updates Wazero accordingly.
Signed-off-by: Edoardo Vacchi <evacchi@users.noreply.github.com>
=> deps: updates wazero to 1.0.0-rc.1 and proxy-wasm-go-sdk to 0.22.0

example/envoy-config.yaml, ftw/Dockerfile, ftw/ftw.yml, go.mod, go.sum, wasmplugin/rules/ftw-config.conf
In order to make https://github.com/corazawaf/coraza/pull/684 work, it is needed to:
- update `tx.paranoia_level outdated` CRS variable into `blocking_paranoia_level`
- add `SecDefaultAction “phase:5,log,auditlog,pass` otherwise correlation rules executed at phase 5 are not logged and ftw is not able to detect that these rules have been triggered.
Please refer to the upstream PRs for details: https://github.com/corazawaf/coraza/pull/684
=> chore: Updates coraza and fixes related CRS configs

README.md, magefiles/magefile.go
add ReloadExample that runs docker-compose reload. This help speeds up the development process since we don't need to teardown & up back the container.
=> feat: add ReloadExample to easily reload the example when testing WASM

example/envoy-config.yaml, wasmplugin/plugin.go
Based on some reports ( see https://github.com/corazawaf/coraza/discussions/594, https://github.com/corazawaf/coraza-proxy-wasm/issues/171#issuecomment-1508428211 and [here](https://owasp.slack.com/archives/C02BXH135AT/p1678237973291379)) the current local response validation based on enforcing that only one header is returned back from a local response is too strict.
It leads to an `Interruption already handled, unexpected local response` error, and the request remains hanging until timeout.
This PR proposes to relax it by:
- Checking it is  an `endOfStream` (no body response) 
- Checking the status is coherent with the status requested by the interruption.
As I wrote in the comments, it would be possible to clean up unexpected headers to reduce even more possible leaks, open to opinions …
=> fix: relaxes local response validation

wasmplugin/plugin.go
Fixes https://github.com/corazawaf/coraza-proxy-wasm/issues/181
Even if an http request is interrupted by a Coraza interruption that triggers a local response, the callback [OnHttpStreamDone](https://github.com/corazawaf/coraza-proxy-wasm/blob/main/wasmplugin/plugin.go#LL464C25-L464C41) is still called and consequently, the logic that runs `ProcessResponseBody` if it has not already been done.
This PR proposes to avoid the described logic if an interruption already happened.
=> avoids running response body in http done if interruption happened

README.md, example/docker-compose.yml, example/envoy-config.yaml, ftw/envoy-config.yaml, main_test.go, wasmplugin/config.go, wasmplugin/config_test.go, wasmplugin/plugin.go
solve https://github.com/corazawaf/coraza-proxy-wasm/issues/180
**Proposal**
1. introducing a list of directives (directives_map), this list of directives_map will have its own transaction & logging object
2. ability to enable default directive(default_directive), if this is enabled, all requests will flow through WAF
3. ability to enable a specific directive per authority (per_authority_directives), this will completely replace the default directive for specific authority defined
| **default_directive** | **per_authority_directives** | Expectation |
|---|---|---|
| global_directive | "foo.example.com": "foo_directive" | 1. foo.example.com will implement foo_directive<br>2. any other authority will implement global_directive  |
| global_directive | N/A | 1. all traffic will implement …
=> feat: introducing dynamic WAF rules based on authority header

.github/workflows/ci.yaml, .github/workflows/release_notes.sh
Closes https://github.com/corazawaf/coraza-proxy-wasm/issues/177.
This PR implements the release CI job. Only on tag creation:
- The build job executes one more step of caching `main.wasm` for the next job.
- Release is triggered after build, restores the cache and creates a draft release with the wasm file renamed as `coraza-proxy-wasm-${tag}.wasm` and an initial changelog template. 
Inspired by https://github.com/tetratelabs/wazero/blob/main/.github/workflows/release.yaml
=> ci: Release job after tag creations

README.md
"@owasp_crs/*.conf" cannot be used without "@crs-setup-demo-conf".
fix https://github.com/corazawaf/coraza-proxy-wasm/issues/189
=> Update "Using CRS" example code

README.md
Fixes https://github.com/corazawaf/coraza-proxy-wasm/issues/195 explicitly stating that tinygo is required and providing a link to see the required version.
=> chore(readme): clarifies project dependencies

.github/workflows/nightly-coraza-check.yaml
Follows https://github.com/corazawaf/coraza/discussions/773 decision about renaming Coraza main branch from `v3/master` to `main`. Fixes Nightly Coraza Check.
=> fix(ci): changes Coraza reference to main brach

main_test.go, wasmplugin/config_test.go, wasmplugin/plugin.go
Fixes https://github.com/corazawaf/coraza-proxy-wasm/issues/198
In this PR I took a different approach compared to https://github.com/corazawaf/coraza-proxy-wasm/pull/199 to not to add another object and also avoiding initialization of WAFs that are not being used by any authority but **I borrowed the tests created in @zufardhiyaulhaq PR's which was awesome**. Thanks for that.
=> fix: authority retrieval by mapping per authority and not per directives name.

.github/workflows/ci.yaml
`contents` scope allows to modify repository's content, it should be the missing needed permission to make `Create Draft Release` step work. (see failing action: https://github.com/corazawaf/coraza-proxy-wasm/actions/runs/5221810741/jobs/9426707613#step:18:38)
=> ci: sets contents write permission to create draft releases

go.mod, go.sum
Notably:
- Updates Coraza to `v3.0.0` (from `v3.0.0-rc3`)
Edit: updated pointing to Coraza `v3.0.0` instead of `v3.0.1-0.20230614023334-2fd87b892906`
=> updates Coraza to v3.0.0 release

go.mod, go.sum
0.3.0 has support for TinyGo 0.28. Unfortunately, it seems this repo doesn't work with 0.28 since one of our codepaths seems to cause `fd_readdir` to be imported when updating... But anyways, getting the code ready to figure out a way to deal with that first
=> Upgrade nottinygc

.github/workflows/close-issues.yml
This PR proposes to use also in this repo the stale label "awaiting feedback", also used in the Coraza repo: https://github.com/corazawaf/coraza/pull/793.
=> Adds stale bot for awaiting-feedback issues

.github/workflows/ci.yaml
Follows #224 addressing https://github.com/corazawaf/coraza-proxy-wasm/pull/224#discussion_r1317252495
Multiple Envoys images are being tested back in the CI:
```
Run for image in $ENVOY_IMAGES; do
Running e2e with Envoy image envoyproxy/envoy:v1.27-latest
Creating network "e2e_default" with the default driver
Pulling httpbin (mccutchen/go-httpbin:v2.9.0)...
v2.9.0: Pulling from mccutchen/go-httpbin
Digest: sha256:9fffd11a43051be0ed27556e09ad9dca0a341769c31ef4699c592ed2b24c6986
Status: Downloaded newer image for mccutchen/go-httpbin:v2.9.0
Pulling envoy (envoyproxy/envoy:v1.27-latest)...
v1.27-latest: Pulling from envoyproxy/envoy
Digest: sha256:3c607686b205188dd035e1a6f30b830ce4e2c1b0dfecac2ccf150796c29abf35
Status: Downloaded newer image for envoyproxy/envoy:v1.27-latest
[...]
[9/9] …
```
=> Adds back e2e against multiple Envoy images

.github/workflows/ci.yaml, .github/workflows/nightly-coraza-check.yaml, magefiles/magefile.go
Was trying to build and noticed my TinyGo was too new. Looks like there is no issue in going ahead and updating
=> Update TinyGo to 0.29

magefiles/magefile.go
This PR enables memoization of builders for `regex` and `aho-corasick` dictionaries to reduce memory consumption in deployments that launch several coraza instances (e.g. several authorities). For more context check https://github.com/corazawaf/coraza-caddy/issues/76
=> feat: uses memoization to decrease memory consumption.

.github/workflows/ci.yaml, .github/workflows/nightly-coraza-check.yaml, go.mod, go.sum, magefiles/magefile.go
tinygo `0.30.0` is out and our tinygo version check is very strict. The update looks okay.
Updated also coraza-wasilibs that includes [go-re2 latest release](https://github.com/wasilibs/go-re2/releases/tag/v1.4.0).
=> Updates to latest tinygo and coraza-wasilibs

magefiles/magefile.go
go version check is now a more generic `checkVersion` function that can be used for both `Go` and `Tinygo`. As noted in https://github.com/corazawaf/coraza-proxy-wasm/pull/231#discussion_r1342557668, Tinygo compatibility lately has been good enough.
=> chore: relaxes tinygo version check

.github/workflows/ci.yaml, README.md, example/envoy/docker-compose.yml, magefiles/magefile.go
- https://github.com/corazawaf/coraza-proxy-wasm/pull/233 moved the envoy example into an inner folder, a small fix to the wasm path is needed to properly run the example.
- A CI test might follow to check that the example correctly loads, but I didn't manage to make it work right now
- Address https://github.com/corazawaf/coraza-proxy-wasm/pull/222#discussion_r1291940544 (avoids `mage` commands in readme)
- Address https://github.com/corazawaf/coraza-proxy-wasm/pull/222#discussion_r1291940432 (removes running the example in detached mode by default. It should simplify the usage and reduce the number of commands to just one to have the example running with logs printed)
=> chore: fixes Wasm path for EnvoyExample, removes detached

.github/workflows/ci.yaml
Attempt to fix https://github.com/corazawaf/coraza-proxy-wasm/actions/runs/7002845798/job/19047393332. Pushing a tag should lead the CI to create a draft release with the artifact attached
=> fix(ci): creation of release if it does not exists

wasmplugin/rules/coraza.conf-recommended.conf
As per https://github.com/corazawaf/coraza-proxy-wasm/pull/243#issuecomment-1821320487, `BodyLimit` and `Memorylimit` values in `demo.conf` have been set to the lower value (`131072`), but not `coraza.conf-recommended.conf`. This PR address it.
=> chore: BodyLimit and Memorylimit to 131072

README.md, magefiles/loadtest.go, magefiles/magefile.go
Incidentally, we started seeing errors since https://github.com/corazawaf/coraza-proxy-wasm/pull/264 has been merged into `main`, but the root cause of CI problems comes from [`Docker Compose v1 will be removed from images on April, 1`](https://github.com/actions/runner-images/issues/9557). This PR moves from `docker-compose` to `docker compose`.
=> fix: removes deprecated docker-compose in favour of docker compose

wasmplugin/plugin.go
I think it is a good feedback if we fail to close a transaction.
=> chore: prints error on closing tx.

main_test.go, wasmplugin/plugin.go
Fix for issue #269 
Retrieves :method before :path to allow request without path if HTTP method is CONNECT.
=> Allow empty path when HTTP method is CONNECT

main_test.go, wasmplugin/plugin.go
Address https://github.com/corazawaf/coraza-proxy-wasm/issues/280#issuecomment-2180886603
=> fix: rely on IsResponseBodyProcessable

.github/workflows/ci.yaml
Address https://github.com/corazawaf/coraza-proxy-wasm/pull/282#discussion_r1659641187. Step before updating to Coraza v3.2.1
=> chore: updates to latest envoy images

.github/workflows/ci.yaml, .github/workflows/nightly-coraza-check.yaml
See https://github.com/corazawaf/coraza-proxy-wasm/pull/301 ci run.
> actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. Please update your workflow to use v4 of the artifact actions. This deprecation will not impact any existing versions of GitHub Enterprise Server being used by customers.
=> fix: ci deprecated actions

magefiles/magefile.go
The build process is failing after 3 minutes ([default tinygo inter timeout](https://github.com/tinygo-org/tinygo/blob/3e60eeb368f25f237a512e7553fd6d70f36dc74c/main.go#L1500)) when trying to build a filter with GeoIP pluging that has a city database embedded:
```
/app/geoip.go:15:6: interp: running for more than 3m0s, timing out (executed calls: 2)
%stackalloc = alloca i8, align 1, !dbg !46
traceback:
/app/geoip.go:15:6:
%stackalloc = alloca i8, align 1, !dbg !46
app:
call void @"main.init#1"(ptr undef), !dbg !44
Error: running "tinygo build -gc=custom -opt=2 -o build/mainraw.wasm -scheduler=none -target=wasip1 -tags='custommalloc nottinygc_envoy no_fs_access memoize_builders coraza.rule.multiphase_evaluation'" failed with exit code 1
```
This change will allow increasing the timeout so …
=> feat(magefile): allow to customise interp timeout
